# Generated by Django 3.2.4 on 2021-06-21 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_game_onlinegamestore_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('ts', 'Tactical Shooter'), ('rpg', 'RPG')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='game_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.gamegenre'),
        ),
    ]
