# Generated by Django 3.2.4 on 2021-06-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20210621_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_genre',
            field=models.CharField(choices=[('ts', 'Tactical Shooter'), ('rpg', 'RPG'), ('mb', 'MOBA')], max_length=50),
        ),
        migrations.DeleteModel(
            name='GameGenre',
        ),
    ]
