# Generated by Django 3.2.4 on 2021-06-21 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_auto_20210621_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_rating',
            new_name='game_fav',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
