# Generated by Django 3.2.4 on 2021-06-21 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0005_auto_20210621_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_fav',
        ),
        migrations.AddField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(related_name='game_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
