# Generated by Django 3.2.4 on 2021-06-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_auto_20210621_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='rel_date',
            field=models.DateField(verbose_name='Date Released'),
        ),
    ]
