# Generated by Django 3.2.4 on 2021-06-21 16:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0007_alter_game_rel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_des',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='game_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
