# Generated by Django 3.2.4 on 2021-06-21 19:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0009_auto_20210621_1846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='onlinegamestore',
            old_name='store_address',
            new_name='store_link',
        ),
        migrations.RemoveField(
            model_name='onlinegamestore',
            name='store_email',
        ),
        migrations.RemoveField(
            model_name='onlinegamestore',
            name='store_postcode',
        ),
    ]
